# Generated by Django 5.2.3 on 2025-06-18 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_propaccount_dayli_draw_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propaccount',
            options={'verbose_name': 'حساب پراپ', 'verbose_name_plural': 'حساب\u200cهای پراپ'},
        ),
        migrations.AddField(
            model_name='propaccount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_accounts', to='trading.proporder', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='propaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prop_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
