# Generated by Django 5.2.3 on 2025-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_propaccount_options_propaccount_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='profit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
