# Generated by Django 5.2.3 on 2025-06-24 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('zero', 'صفر'), ('single_stage', 'تک\u200cمرحله\u200cای'), ('two_stage', 'دو مرحله\u200cای')], max_length=100)),
                ('account_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leverage', models.CharField(default='1:100', max_length=10)),
            ],
            options={
                'verbose_name': 'پلن پراپ',
                'verbose_name_plural': 'پلن\u200cهای پراپ',
            },
        ),
        migrations.AlterModelOptions(
            name='proporder',
            options={'verbose_name': 'سفارش پراپ', 'verbose_name_plural': 'سفارش\u200cهای پراپ'},
        ),
        migrations.RemoveField(
            model_name='propaccount',
            name='dayli_draw_percent',
        ),
        migrations.RemoveField(
            model_name='propaccount',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='propaccount',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='proporder',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='propaccount',
            name='daily_draw_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proporder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='proporder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='floating_risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_accounts', to='trading.proporder'),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='profit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='total_draw_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prop_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PlanStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('stage_one', 'مرحله اول'), ('stage_two', 'مرحله دوم'), ('real', 'ریل')], max_length=20)),
                ('profit_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_target_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_loss_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_daily_loss_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_trading_days', models.IntegerField(blank=True, null=True)),
                ('floating_risk_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='trading.propplan')),
            ],
            options={
                'verbose_name': 'مرحله پلن',
                'verbose_name_plural': 'مراحل پلن',
            },
        ),
        migrations.AddField(
            model_name='propaccount',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='trading.propplan'),
        ),
        migrations.AddField(
            model_name='proporder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.propplan'),
        ),
    ]
