# Generated by Django 5.2.3 on 2025-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_propplan_alter_proporder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propplan',
            name='name',
            field=models.CharField(choices=[('zero', 'ریل'), ('single_stage', 'تک\u200cمرحله\u200cای'), ('two_stage', 'دو مرحله\u200cای')], max_length=100),
        ),
    ]
