# Generated by Django 5.2.3 on 2025-06-25 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_propplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_image', models.ImageField(upload_to='identity/national_id/%Y/%m/%d/', verbose_name='تصویر کارت ملی')),
                ('selfie_with_id_image', models.ImageField(upload_to='identity/selfie/%Y/%m/%d/', verbose_name='سلفی با کارت ملی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد شدن')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'احراز هویت',
                'verbose_name_plural': 'احراز هویت\u200cها',
            },
        ),
    ]
