# Generated by Django 5.2.3 on 2025-06-25 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trading', '0009_identityverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='national_id_image',
            field=models.ImageField(upload_to='identity/national_id/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='selfie_with_id_image',
            field=models.ImageField(upload_to='identity/selfie/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_accounts', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_manage_tickets', models.BooleanField(default=False)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_manage_verifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
