# Generated by Django 5.2.3 on 2025-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_ticket_user_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_plans',
            field=models.BooleanField(default=False),
        ),
    ]
