# Generated by Django 5.2.3 on 2025-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='propplan',
            name='level',
            field=models.CharField(choices=[('stage_one', 'مرحله اول'), ('stage_two', 'مرحله دوم'), ('real', 'ریل')], default='stage_one', max_length=20),
        ),
    ]
