# Generated by Django 5.2.3 on 2025-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_propplan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='payment_method',
            field=models.CharField(choices=[('tether', 'تتر'), ('rial', 'ریالی')], default='tether', max_length=20),
        ),
        migrations.AddField(
            model_name='proporder',
            name='server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
