# Generated by Django 5.2.3 on 2025-06-27 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_proporder_payment_method_proporder_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصد'), ('amount', 'مقدار ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده')),
                ('max_uses_active', models.BooleanField(default=False, verbose_name='فعال بودن محدودیت استفاده')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='فقط برای خرید اول')),
                ('affiliate_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل معرف')),
                ('affiliate_percentage', models.FloatField(default=0.0, verbose_name='درصد معرف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('plans', models.ManyToManyField(blank=True, to='trading.propplan', verbose_name='پلن\u200cهای مجاز')),
                ('users', models.ManyToManyField(blank=True, related_name='allowed_discount_users', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
