# Generated by Django 5.2.3 on 2025-06-27 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='proporder',
            name='final_price_toman',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت نهایی (تومان)'),
        ),
        migrations.AddField(
            model_name='proporder',
            name='final_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نهایی (دلار)'),
        ),
        migrations.AddField(
            model_name='proporder',
            name='original_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت اصلی (دلار)'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='payment_method',
            field=models.CharField(choices=[('tether', 'تتر'), ('rial', 'ریالی')], default='tether', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.propplan', verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بروکر'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='proporder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
