# Generated by Django 5.2.3 on 2025-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_proporder_discount_code_proporder_final_price_toman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_discounts',
            field=models.BooleanField(default=False),
        ),
    ]
