# Generated by Django 5.2.3 on 2025-06-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_employee_can_manage_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='investor_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='main_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='server',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
