# Generated by Django 5.2.3 on 2025-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_alter_propaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
