# Generated by Django 5.2.3 on 2025-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_propaccount_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaccount',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('profit_withdrawal', 'برداشت سود'), ('lost', 'از دست رفته'), ('frozen', 'فریز')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='propaccount',
            name='level',
            field=models.CharField(blank=True, choices=[('level1', 'مرحله اول'), ('level2', 'مرحله دوم'), ('Real', 'ریل')], max_length=50, null=True),
        ),
    ]
