# Generated by Django 5.2.3 on 2025-07-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_propaccount_status_alter_propaccount_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliate_percentage',
            field=models.FloatField(default=0.0, verbose_name='درصد همکاری رفرال'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL, verbose_name='معرفی\u200cشده')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL, verbose_name='معرف')),
            ],
            options={
                'verbose_name': 'رفرال',
                'verbose_name_plural': 'رفرال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='موجودی (دلار)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
    ]
