# Generated by Django 5.2.3 on 2025-07-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_customuser_affiliate_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
