# Generated by Django 5.2.3 on 2025-07-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propplan',
            name='name',
            field=models.CharField(choices=[('zero', 'ریل'), ('single_stage', 'تک\u200cمرحله\u200cای'), ('two_stage', 'دو مرحله\u200cای'), ('weekly', 'هفتگی')], max_length=100),
        ),
    ]
