# Generated by Django 5.2.3 on 2025-07-26 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_alter_propplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد درخواست')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='trading.propaccount', verbose_name='حساب پراپ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست ارتقاء مرحله',
                'verbose_name_plural': 'درخواست\u200cهای ارتقاء مرحله',
                'unique_together': {('account', 'user')},
            },
        ),
    ]
