# Generated by Django 5.2.3 on 2025-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='used_wallet',
            field=models.BooleanField(default=False, verbose_name='استفاده از کیف پول'),
        ),
    ]
