# Generated by Django 5.2.3 on 2025-09-14 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_proporder_used_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='درآمد رفرال'),
        ),
    ]
