# Generated by Django 5.2.3 on 2025-09-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_referral_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='trading.propaccount', verbose_name='حساب پراپ'),
        ),
    ]
