# Generated by Django 5.2.3 on 2025-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_ticket_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propplan',
            name='name',
            field=models.CharField(choices=[('zero', 'ریل'), ('single_stage', 'تک\u200cمرحله\u200cای'), ('two_stage', 'دو مرحله\u200cای'), ('weekly', 'هفتگی'), ('two_stage_lottery', 'دو مرحله\u200cای (قرعه\u200cکشی)')], max_length=100),
        ),
    ]
