# Generated by Django 5.2.3 on 2025-09-18 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_alter_propplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAccountQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='تاریخ')),
                ('total_capacity', models.PositiveIntegerField(default=100, verbose_name='ظرفیت کل')),
                ('allocated_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تخصیص\u200cیافته')),
            ],
            options={
                'verbose_name': 'ظرفیت اکانت رایگان',
                'verbose_name_plural': 'ظرفیت\u200cهای اکانت رایگان',
            },
        ),
    ]
