# Generated by Django 5.2.3 on 2025-09-28 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_freeaccountquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روی سرتیفیکیت')),
                ('file', models.FileField(upload_to='certificates/%Y/%m/%d/', verbose_name='فایل سرتیفیکیت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='trading.propaccount', verbose_name='حساب پراپ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سرتیفیکیت',
                'verbose_name_plural': 'سرتیفیکیت\u200cها',
            },
        ),
    ]
