# Generated by Django 5.2.3 on 2025-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_alter_referral_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
