# Generated by Django 5.2.3 on 2026-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت دلاری'),
        ),
    ]
