# Generated by Django 6.0.3 on 2026-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_proporder_dollar_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره حساب')),
                ('broker', models.CharField(blank=True, max_length=50, verbose_name='بروکر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل کاربر')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره سفارش')),
                ('plan', models.CharField(blank=True, max_length=100, null=True, verbose_name='پلن')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='لول')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='بالانس اولیه')),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='بالانس نهایی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بررسی')),
            ],
            options={
                'verbose_name': 'لاگ شبیه\u200cسازی حساب',
                'verbose_name_plural': 'لاگ\u200cهای شبیه\u200cسازی حساب',
                'ordering': ['-checked_at'],
            },
        ),
    ]
