# Generated by Django 6.0.3 on 2026-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_accountsimulationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propaccount',
            options={'ordering': ['-updated_at'], 'verbose_name': 'حساب پراپ', 'verbose_name_plural': 'حساب\u200cهای پراپ'},
        ),
        migrations.AddField(
            model_name='propaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به\u200cروزرسانی'),
        ),
    ]
