# Generated by Django 6.0.3 on 2026-06-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_alter_propaccount_options_propaccount_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه'),
        ),
    ]
