# Generated by Django 6.0.3 on 2026-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_proporder_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proporder',
            name='accnum',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='اکانت تحویلی'),
        ),
    ]
