# Generated by Django 6.0.3 on 2026-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_proporder_accnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_rial_gateway', models.CharField(choices=[('directpay', 'دایرکت پی'), ('paystar', 'پی\u200cاستار')], default='directpay', max_length=20, verbose_name='درگاه ریالی فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه پرداخت',
                'verbose_name_plural': 'تنظیمات درگاه پرداخت',
            },
        ),
        migrations.AddField(
            model_name='proporder',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='درگاه پرداخت'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='درگاه پرداخت'),
        ),
    ]
