# Generated by Django 5.2.3 on 2025-07-17 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, verbose_name='آیدی اینستاگرام')),
                ('telegram_id', models.CharField(max_length=100, verbose_name='آیدی تلگرام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'ارسال اطلاعات کاربر',
                'verbose_name_plural': 'ارسال\u200cهای اطلاعات کاربران',
            },
        ),
    ]
