# Generated by Django 5.2.3 on 2025-07-17 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='آدرس IP')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('last_attempt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین تلاش')),
            ],
            options={
                'verbose_name': 'تلاش ارسال',
                'verbose_name_plural': 'تلاش\u200cهای ارسال',
            },
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
