# Generated by Django 6.0.3 on 2026-06-28 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_submissionattempt_alter_usersubmission_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, db_index=True, max_length=254, verbose_name='ایمیل ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='سوپریوزر بود')),
                ('category', models.CharField(choices=[('view', 'بازدید'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('action', 'عملیات')], db_index=True, default='view', max_length=10, verbose_name='نوع عملیات')),
                ('action_description', models.CharField(blank=True, max_length=300, verbose_name='شرح عملیات')),
                ('method', models.CharField(db_index=True, max_length=10, verbose_name='متد HTTP')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='مسیر')),
                ('view_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='نام ویو')),
                ('query_string', models.TextField(blank=True, verbose_name='پارامترهای کوئری')),
                ('post_data', models.TextField(blank=True, verbose_name='داده\u200cهای ارسالی')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه آبجکت')),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='کد وضعیت پاسخ')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'لاگ عملیات ادمین',
                'verbose_name_plural': 'لاگ\u200cهای عملیات ادمین',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_panel_created_e4dd82_idx'), models.Index(fields=['user_email', '-created_at'], name='admin_panel_user_em_29c2e1_idx')],
            },
        ),
    ]
